config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'

  get 'admins/new'

  get 'admins/show'

  get 'admins/edit'

  root to: 'homes#index'

  resources :billings 

  resources :rooms

  devise_for :users

  resources :users

  resources :reservations

  get 'homes/show'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

  get 'users/home'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  
end

app/models/billing.rb
class Billing < ApplicationRecord

  belongs_to :reservation

end

app/models/hotel.rb
class Hotel < ApplicationRecord

  validates :phone_number, presence:true, length: { maximum: 10 },numericality: { only_integer: true }

  validates :name, presence: true

  validates :address, presence: true

  validates :city, presence: true

  validates :state, presence: true

  has_many :rooms

  has_many :reservations
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord

	validates :first_name, presence: true

	validates :last_name, presence: true

	validates :status, presence: true

	validates :room_type, presence: true

	has_many :billings

	belongs_to :room

	belongs_to :user 
	
	belongs_to :hotel 

	enum status: { available:0, unavailable:1 }
	
	enum room_type: { single:0, double:1, delux:2 }

end

app/models/room.rb
class Room < ApplicationRecord

	has_many :reservations

	belongs_to :hotel
	 
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :city, presence: true

  validates :state, presence: true

  validates :country, presence: true

  has_many :reservations

  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable 

  enum role: { user:0, admin:1 }

end 

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
  end

  def new
  end

  def show
  end

  def edit
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pagy::Backend
  
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(reservations)
    reservations_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :role, :first_name, :last_name, :city, :state, :country])
  end

end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

  def index
    @pagy,@billings = pagy(Billing.order(created_at: :desc),items:4)
  end

  def show
    @billing = Billing.find(params[:id])
  end

  def new
    @billing = Billing.new
  end

  def create
    @billing = Billing.new(billing_params)
    if @billing.save
      redirect_to @billing
    else
      render 'new'
    end
  end
  
  def edit
    @billing = Billing.find(params[:id])
  end

  def update
    @billing = Billing.find(params[:id])
    if @billing.update(billing_params)
      redirect_to @billing
    else
      render 'edit'
    end
  end

  def destroy
    @billing = Billing.find(params[:id])
    @billing.destroy
    redirect_to billings_path
  end

  private
  def billing_params
    params.require(:billing).permit(:room_type, :number_of_nights, :night_rate, :total_amount, :reservation_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    
  end

  def home

  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @pagy,@reservations = pagy(Reservation.order(created_at: :desc),items:5)
    @q = Reservation.ransack(params[:q])
    @reservations = @q.result(distinct: true)
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def create
    @reservation = current_user.reservations.new(reservation_params)
    if @reservation.save
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      redirect_to @reservation
    else
      render 'edit'
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path
  end

  private
  def reservation_params
    params.require(:reservation).permit(:first_name, :last_name, :phone_number, :number_of_people, :description, :status, :room_id, :user_id, :hotel_id, :search)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to billings_path	
    else
      render 'new'
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to @room
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  private
  def room_params
    params.require(:room).permit(:name, :phone, :check_in, :check_out, :number_of_nights, :hotel_id, :user_id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :is_admin?

  def home

  end

  def is_admin?
    redirect_to root_path unless current_user.admin?
  end

  def index
    @users=User.all
  end

  def show

  end

  def new

  end

  def edit

  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/edit.html.erb
<h1>Admins#edit</h1>
<p>Find me in app/views/admins/edit.html.erb</p>

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<p>Find me in app/views/admins/index.html.erb</p>

app/views/admins/new.html.erb
<h1>Admins#new</h1>
<p>Find me in app/views/admins/new.html.erb</p>

app/views/admins/show.html.erb
<h1>Admins#show</h1>
<p>Find me in app/views/admins/show.html.erb</p>

app/views/billings/_form.html.erb
<h1>Billing </h1>
<%= form_with model: @billing, local: true do |form| %>
  <% if @billing.errors.any? %>
  <div id="error_explanation">
  <h2>
  <%= pluralize(@billing.errors.count, "error") %> prohibited this billing from being saved:
  </h2>
  <ul>
  <% @billing.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
    
    <div class="field">
    <%= form.label :room_type %>
    <%= form.select :room_type, [ 'Select', 'Single', 'Double', 'Delux' ] %>
    </div><br>
    
    <div class="field">
    <%= form.label :number_of_nights %>
    <%= form.select :number_of_nights, [ 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15 ] %>
    </div><br>
    
    <div class="field">
    <%= form.label :night_rate %>
    <%= form.select :night_rate, [ 10000, 15000, 20000, 25000, 30000 ] %>
    </div><br>
    
    <div class="field">
    <%= form.label :total_amount %>
    <%= form.text_field :total_amount, id: :billing_total_amount %>
    </div><br>
    
    <p>
    <%= form.label :reservation_id %><br>
    <%= form.select :reservation_id, Reservation.all.collect { |b| [ b.id ]  } %>
    </p>
    
    <p>
    <%= form.submit"book now" %>
    </p>
    <% end %>

app/views/billings/edit.html.erb
<%= render 'form', billing: @billing %>
<%= link_to 'Show', @billing %> |
<%= link_to 'Back', billings_path %>

app/views/billings/index.html.erb
<ul class="nav justify-content-center">
<li class="nav-item">
<%= link_to 'Create Billing', new_billing_path %>
</li>
</ul>
<br>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %><br>

<table class="table">
<thead>
    <tr>
      <th scope="col">Room Type</th>
      <th scope="col">Number Of Nights</th>
      <th scope="col">Night Rates</th>
      <th scope="col">Total Amount</th>
      <th colspan="5"></th>
    </tr>
</thead>
<tbody>
<% @billings.each do |billing| %>
  <tr>
      <td><%= billing.room_type %></td>
      <td><%= billing.number_of_nights %></td>
      <td><%= billing.night_rate %></td>
      <td><%= billing.total_amount %></td>
      <td><%= link_to 'Show', billing %></td>
      <td><%= link_to 'Edit', edit_billing_path(billing) %></td>
      <td><%= link_to 'Destroy', billing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Back', rooms_path	%></td>
      <td><%= link_to 'PDF', billing_path(billing, format: :pdf) %></td>
      </tr>
      <% end %>
</tbody>
</table>
<br>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/billings/new.html.erb
<%= render 'form', billing: @billing %>
<%= link_to 'Back', billings_path %>

app/views/billings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
   <strong> room Type:</strong>
   <%= @billing.room_type %>
</p>

<p>
   <strong>Number Of Nights:</strong>
   <%= @billing.number_of_nights %>
</p>

<p>
   <strong>Night Rate:</strong>
   <%= @billing.night_rate %>
</p>

<p>
   <strong>Total Amount:</strong>
   <%= @billing.total_amount %>
</p>

<%= link_to 'Edit', edit_billing_path(@billing) %> |
<%= link_to 'Back', billings_path %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="text-center text-white" style="background-color: #caced1;">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Images -->
    <section class="">
      <div class="row">
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/113.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/111.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/112.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/114.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/115.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/116.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- Section: Images -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 allrightreserved:
    <a class="text-white" href="https://www.booking.com/index.en-gb.html?aid=1610687&label=indore-cLCQI6bHFVTDfQbU46faFQS379234773574%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-11234152482%3Alp9300952%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YfpWGnRw6lOGgfEoJVv7zYo&sid=f3f7b6ba0910225d1d10b26877095d18&click_from_logo=1">Gurukripa.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand  text-dark" href="#">Hotel Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active text-dark" aria-current="page" href="#">Home</a>
      </li>
  </ul>
    </div>
  <ul class="nav justify-content-end ">
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      <li class="nav-item ">
        
      </li>
  </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>MyApp</title>
<%= csrf_meta_tags %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
      <% if current_user %>
      <%= render 'layouts/navbar' %>
      <% else %>
      <%= link_to 'Sign up', new_user_registration_path %>
      <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
      <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      </div>
</body>
 </html>

app/views/reservations/_form.html.erb
<h1>Registration Form</h1>
<%= form_with model: @reservation, local: true do |form| %> 
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reservation.errors.count, "error") %> prohibited
        this reservation from being saved:
      </h2>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <br>

<div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :reservation_first_name %>
</div><br>
 
<div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :reservation_last_name %>
</div><br>

<div class="field">
  <%= form.label :phone_number %>
  <%= form.text_field :phone_number, id: :reservation_phone_number %>
</div><br>

<div class="field">
  <%= form.label :status %>
  <%= form.select :status, ['available']%>
</div><br>

<div class="field">
  <%= form.label :room_type %>
  <%= form.select :room_type, ['single', 'double', 'delux']%>
</div><br>

<div class="field">
  <%= form.label :number_of_people %>
  <%= form.select :number_of_people, [ 1, 2, 3, 4, 5 ]%>
</div><br>

<div class="field">
  <%= form.label :"Do you have special request" %>
  <%= form.text_area :description, id: :reservation_description %>
</div><br>

<p>
  <%= form.label :room_id %><br />
  <%= form.select :room_id, Room.all.collect { |b| [ b.id ]  } %>
</p><br>

<p>
  <%= form.label :hotel_id %><br />
  <%= form.select :hotel_id, Hotel.all.collect { |a| [ a.id ]  } %>
</p><br>

<p>
  <%= form.submit "submit" %>
</p>

<% end %>

app/views/reservations/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <%= f.search_field :first_name_start, placeholder: "Search First name..." %>
    <%= f.submit "First Name!" %>
    <%= f.search_field :last_name_start, placeholder: "Search Last name..." %>
    <%= f.submit "Last Name!" %>
<% end %>

app/views/reservations/edit.html.erb
<div class="col-lg-8">
<h1>Editing Reservation</h1>
<%= render 'form', reservation: @reservation %>
</div>
<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<!--
<h1>
Reservations :
<%= @reservations.count %>
/
<%= Reservation.count %>
</h1>
-->
<br>
<ul class="nav justify-content-center">
<li class="nav-item">
<%= link_to 'New Reservation', new_reservation_path %>
</li>
</ul><br>

<%= render 'reservations/search_form' %>

<table class="table">
  <thead>
    <tr>
    <th><%= sort_link(@q, :first_name, "First Name", default_order: :asc) %></th>
      <%# <th scope="col" >First Name</th> %>
    <th><%= sort_link(@q, :last_name, "Last Name", default_order: :asc) %></th>
      <%# <th scope="col" >Last Name</th> %>
      <th scope="col" >Phone Number</th>
      <th scope="col" >Status</th>
      <th scope="col" >Room Type</th>
      <th scope="col" >Number Of People</th>
      <th scope="col" >Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.first_name %></td>
        <td><%= reservation.last_name %></td>
        <td><%= reservation.phone_number %></td>
        <td><%= reservation.status %></td>
        <td><%= reservation.room_type %></td>
        <td><%= reservation.number_of_people %></td>
        <td><%= reservation.description %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Next', rooms_path	%></td>
      </tr>
    <% end %>
  </tbody>
</table><br>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/reservations/new.html.erb
<%= render 'form', reservation: @reservation %>
<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p>
  <strong>Fname:</strong>
  <%= @reservation.first_name %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @reservation.last_name %>
</p>

<p>
  <strong>phone number:</strong>
  <%= @reservation.phone_number %>
</p>

<p>
  <strong>status:</strong>
  <%= @reservation.status %>
</p>

<p>
  <strong>room type:</strong>
  <%= @reservation.room_type %>
</p>

<p>
  <strong>number of people:</strong>
  <%= @reservation.number_of_people %>
</p>

<p>
  <strong>description:</strong>
  <%= @reservation.description %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/rooms/_form.html.erb
<h1>Booking Room </h1>
<%= form_with model: @room, local: true do |form| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
    <h2>
      <%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:
    </h2>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
    <% end %>
    
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_name %>
  </div><br>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :room_phone %>
  </div><br>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.date_field  :check_in, id: :room_check_in %>
  </div><br>
  
  <div class="field">
    <%= form.label :check_out %>
    <%= form.date_field  :check_out, id: :room_check_out %>
  </div><br>

  <div class="field">
    <%= form.label :number_of_nights %>
    <%= form.select :number_of_nights, [ 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15 ] %>
  </div><br>

  <div class="field">
    <%= form.label :hotel_id %><br />
    <%= form.select :hotel_id, Hotel.all.collect { |a| [ a.id ]  } %>
  </div>
  
  
  
  <p>
    <%= form.submit"book now" %>
  </p>
  
  <% end %>

app/views/rooms/edit.html.erb
<%= render 'form', room: @room %>
<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1 >Find Rooms</h1>
<%= render 'rooms/search_form' %>
<table class="table">
  <thead>
    <tr>
      <th scope="col" >Name</th>
      <th scope="col" >Phone</th>
      <th scope="col" >Check In</th>
      <th scope="col" >Check Out</th>
      <th scope="col" >Number Of Nights </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.phone %></td>
        <td><%= room.check_in %></td>
        <td><%= room.check_out %></td>
        <td><%= room.number_of_nights %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Back', reservations_path	%></td>
        <td><%= link_to 'Next', billings_path	%></td>
      </tr>
    <% end %>
  </tbody>
</table><br>
<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>
<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @room.phone %>
</p>

<p>
  <strong>check_in:</strong>
  <%= @room.check_in %>
</p>

<p>
  <strong>check_out:</strong>
  <%= @room.check_out %>
</p>

<p>
  <strong>number_of_nights:</strong>
  <%= @room.number_of_nights %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/home.html.erb
<h1>Home Page</h1>
<% if current_user %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to 'Sign up', new_user_registration_path %>
<%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>